/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20160918
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.CoreService.Requests;
using Oci.CoreService.Responses;
using Oci.CoreService.Models;
using Oci.Common.Model;

namespace Oci.CoreService.Cmdlets
{
    [Cmdlet("Update", "OCIVirtualNetworkRemotePeeringConnection")]
    [OutputType(new System.Type[] { typeof(Oci.CoreService.Models.RemotePeeringConnection), typeof(Oci.CoreService.Responses.UpdateRemotePeeringConnectionResponse) })]
    public class UpdateOCIVirtualNetworkRemotePeeringConnection : OCIVirtualNetworkCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the remote peering connection (RPC).")]
        public string RemotePeeringConnectionId { get; set; }

        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"Request to the update the peering connection to remote region")]
        public UpdateRemotePeeringConnectionDetails UpdateRemotePeeringConnectionDetails { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"For optimistic concurrency control. In the PUT or DELETE call for a resource, set the `if-match` parameter to the value of the etag from a previous GET or POST response for that resource. The resource will be updated or deleted only if the etag you provide matches the resource's current etag value.")]
        public string IfMatch { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            UpdateRemotePeeringConnectionRequest request;

            try
            {
                request = new UpdateRemotePeeringConnectionRequest
                {
                    RemotePeeringConnectionId = RemotePeeringConnectionId,
                    UpdateRemotePeeringConnectionDetails = UpdateRemotePeeringConnectionDetails,
                    IfMatch = IfMatch
                };

                response = client.UpdateRemotePeeringConnection(request).GetAwaiter().GetResult();
                WriteOutput(response, response.RemotePeeringConnection);
                FinishProcessing(response);
            }
            catch (OciException ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private UpdateRemotePeeringConnectionResponse response;
    }
}
