/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20160918
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.CoreService.Requests;
using Oci.CoreService.Responses;
using Oci.CoreService.Models;
using Oci.Common.Model;

namespace Oci.CoreService.Cmdlets
{
    [Cmdlet("Update", "OCIBlockstorageVolumeGroupBackup")]
    [OutputType(new System.Type[] { typeof(Oci.CoreService.Models.VolumeGroupBackup), typeof(Oci.CoreService.Responses.UpdateVolumeGroupBackupResponse) })]
    public class UpdateOCIBlockstorageVolumeGroupBackup : OCIBlockstorageCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The Oracle Cloud ID (OCID) that uniquely identifies the volume group backup.")]
        public string VolumeGroupBackupId { get; set; }

        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"Update volume group backup fields")]
        public UpdateVolumeGroupBackupDetails UpdateVolumeGroupBackupDetails { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"For optimistic concurrency control. In the PUT or DELETE call for a resource, set the `if-match` parameter to the value of the etag from a previous GET or POST response for that resource. The resource will be updated or deleted only if the etag you provide matches the resource's current etag value.")]
        public string IfMatch { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            UpdateVolumeGroupBackupRequest request;

            try
            {
                request = new UpdateVolumeGroupBackupRequest
                {
                    VolumeGroupBackupId = VolumeGroupBackupId,
                    UpdateVolumeGroupBackupDetails = UpdateVolumeGroupBackupDetails,
                    IfMatch = IfMatch
                };

                response = client.UpdateVolumeGroupBackup(request).GetAwaiter().GetResult();
                WriteOutput(response, response.VolumeGroupBackup);
                FinishProcessing(response);
            }
            catch (OciException ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private UpdateVolumeGroupBackupResponse response;
    }
}
