/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20210630
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.DevopsService.Requests;
using Oci.DevopsService.Responses;
using Oci.DevopsService.Models;

namespace Oci.DevopsService.Cmdlets
{
    [Cmdlet("Get", "OCIDevopsRepoFileDiff")]
    [OutputType(new System.Type[] { typeof(Oci.DevopsService.Models.FileDiffResponse), typeof(Oci.DevopsService.Responses.GetRepoFileDiffResponse) })]
    public class GetOCIDevopsRepoFileDiff : OCIDevopsCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique repository identifier.")]
        public string RepositoryId { get; set; }

        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The branch to compare changes against.")]
        public string BaseVersion { get; set; }

        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The branch where changes are coming from.")]
        public string TargetVersion { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"A filter to return only commits that affect any of the specified paths.")]
        public string FilePath { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Boolean to indicate whether to use merge base or most recent revision.")]
        public System.Nullable<bool> IsComparisonFromMergeBase { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique Oracle-assigned identifier for the request.  If you need to contact Oracle about a particular request, provide the request ID.")]
        public string OpcRequestId { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            GetRepoFileDiffRequest request;

            try
            {
                request = new GetRepoFileDiffRequest
                {
                    RepositoryId = RepositoryId,
                    BaseVersion = BaseVersion,
                    TargetVersion = TargetVersion,
                    FilePath = FilePath,
                    IsComparisonFromMergeBase = IsComparisonFromMergeBase,
                    OpcRequestId = OpcRequestId
                };

                response = client.GetRepoFileDiff(request).GetAwaiter().GetResult();
                WriteOutput(response, response.FileDiffResponse);
                FinishProcessing(response);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private GetRepoFileDiffResponse response;
    }
}
