/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20200630
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.ApmtracesService.Requests;
using Oci.ApmtracesService.Responses;
using Oci.ApmtracesService.Models;
using Oci.Common.Model;

namespace Oci.ApmtracesService.Cmdlets
{
    [Cmdlet("Get", "OCIApmtracesAggregatedSnapshot")]
    [OutputType(new System.Type[] { typeof(Oci.ApmtracesService.Models.AggregatedSnapshot), typeof(Oci.ApmtracesService.Responses.GetAggregatedSnapshotResponse) })]
    public class GetOCIApmtracesAggregatedSnapshot : OCITraceCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The APM Domain ID for the intended request.")]
        public string ApmDomainId { get; set; }

        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique Application Performance Monitoring trace identifier (traceId).")]
        public string TraceKey { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique Oracle-assigned identifier for the request.  If you need to contact Oracle about a particular request, please provide the request ID.")]
        public string OpcRequestId { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Name associated with the service.")]
        public string ServiceName { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Name of the server.")]
        public string ServerName { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique Application Performance Monitoring span identifier (spanId).")]
        public string SpanKey { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Name of the span associated with the trace.")]
        public string SpanName { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            GetAggregatedSnapshotRequest request;

            try
            {
                request = new GetAggregatedSnapshotRequest
                {
                    ApmDomainId = ApmDomainId,
                    TraceKey = TraceKey,
                    OpcRequestId = OpcRequestId,
                    ServiceName = ServiceName,
                    ServerName = ServerName,
                    SpanKey = SpanKey,
                    SpanName = SpanName
                };

                response = client.GetAggregatedSnapshot(request).GetAwaiter().GetResult();
                WriteOutput(response, response.AggregatedSnapshot);
                FinishProcessing(response);
            }
            catch (OciException ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private GetAggregatedSnapshotResponse response;
    }
}
