<!-- Generated using OracleSDKGenerator, API Version: 20260101 -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>OCI.PSModules.Distributeddatabasev26</AssemblyName>
    <PackageId>OCI.PSModules.Distributeddatabasev26</PackageId>
    <Authors>Oracle Cloud Infrastructure</Authors>
    <Company>Oracle</Company>
    <LangVersion>8.0</LangVersion>
    <PackageTags>Oracle;OCI;Cloud;oci-sdk;OracleCloudInfrastructure;Distributeddatabasev26</PackageTags>
    <Description>Distributeddatabasev26 Service</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OCI.DotNetSdk.Distributeddatabasev26" Version="$(SDKVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\OCI.PSModules.Common.csproj" />
  </ItemGroup>

</Project>
