/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20200501
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.NetworkloadbalancerService.Requests;
using Oci.NetworkloadbalancerService.Responses;
using Oci.NetworkloadbalancerService.Models;

namespace Oci.NetworkloadbalancerService.Cmdlets
{
    [Cmdlet("Get", "OCINetworkloadbalancerHealth")]
    [OutputType(new System.Type[] { typeof(Oci.NetworkloadbalancerService.Models.NetworkLoadBalancerHealth), typeof(Oci.NetworkloadbalancerService.Responses.GetNetworkLoadBalancerHealthResponse) })]
    public class GetOCINetworkloadbalancerHealth : OCINetworkLoadBalancerCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the network load balancer to update.")]
        public string NetworkLoadBalancerId { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"The unique Oracle-assigned identifier for the request. If you must contact Oracle about a particular request, then provide the request identifier.")]
        public string OpcRequestId { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            GetNetworkLoadBalancerHealthRequest request;

            try
            {
                request = new GetNetworkLoadBalancerHealthRequest
                {
                    NetworkLoadBalancerId = NetworkLoadBalancerId,
                    OpcRequestId = OpcRequestId
                };

                response = client.GetNetworkLoadBalancerHealth(request).GetAwaiter().GetResult();
                WriteOutput(response, response.NetworkLoadBalancerHealth);
                FinishProcessing(response);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private GetNetworkLoadBalancerHealthResponse response;
    }
}
