/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20211101
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.MediaservicesService.Requests;
using Oci.MediaservicesService.Responses;
using Oci.MediaservicesService.Models;
using Oci.Common.Model;

namespace Oci.MediaservicesService.Cmdlets
{
    [Cmdlet("Get", "OCIMediaservicesMediaWorkflowJobFact")]
    [OutputType(new System.Type[] { typeof(Oci.MediaservicesService.Models.MediaWorkflowJobFact), typeof(Oci.MediaservicesService.Responses.GetMediaWorkflowJobFactResponse) })]
    public class GetOCIMediaservicesMediaWorkflowJobFact : OCIMediaServicesCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique MediaWorkflowJob identifier.")]
        public string MediaWorkflowJobId { get; set; }

        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"Identifier of the MediaWorkflowJobFact within a MediaWorkflowJob.")]
        public System.Nullable<int> Key { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"The client request ID for tracing.")]
        public string OpcRequestId { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            GetMediaWorkflowJobFactRequest request;

            try
            {
                request = new GetMediaWorkflowJobFactRequest
                {
                    MediaWorkflowJobId = MediaWorkflowJobId,
                    Key = Key,
                    OpcRequestId = OpcRequestId
                };

                response = client.GetMediaWorkflowJobFact(request).GetAwaiter().GetResult();
                WriteOutput(response, response.MediaWorkflowJobFact);
                FinishProcessing(response);
            }
            catch (OciException ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private GetMediaWorkflowJobFactResponse response;
    }
}
