/*
 * NOTE: Generated using OracleSDKGenerator, API Version: 20180222
 * DO NOT EDIT this file manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

using System;
using System.Management.Automation;
using Oci.ContainerengineService.Requests;
using Oci.ContainerengineService.Responses;
using Oci.ContainerengineService.Models;

namespace Oci.ContainerengineService.Cmdlets
{
    [Cmdlet("Get", "OCIContainerengineClusterMigrateToNativeVcnStatus")]
    [OutputType(new System.Type[] { typeof(Oci.ContainerengineService.Models.ClusterMigrateToNativeVcnStatus), typeof(Oci.ContainerengineService.Responses.GetClusterMigrateToNativeVcnStatusResponse) })]
    public class GetOCIContainerengineClusterMigrateToNativeVcnStatus : OCIContainerEngineCmdlet
    {
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, HelpMessage = @"The OCID of the cluster.")]
        public string ClusterId { get; set; }

        [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, HelpMessage = @"Unique Oracle-assigned identifier for the request. If you need to contact Oracle about a particular request, please provide the request ID.")]
        public string OpcRequestId { get; set; }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            GetClusterMigrateToNativeVcnStatusRequest request;

            try
            {
                request = new GetClusterMigrateToNativeVcnStatusRequest
                {
                    ClusterId = ClusterId,
                    OpcRequestId = OpcRequestId
                };

                response = client.GetClusterMigrateToNativeVcnStatus(request).GetAwaiter().GetResult();
                WriteOutput(response, response.ClusterMigrateToNativeVcnStatus);
                FinishProcessing(response);
            }
            catch (Exception ex)
            {
                TerminatingErrorDuringExecution(ex);
            }
        }

        protected override void StopProcessing()
        {
            base.StopProcessing();
            TerminatingErrorDuringExecution(new OperationCanceledException("Cmdlet execution interrupted"));
        }

        private GetClusterMigrateToNativeVcnStatusResponse response;
    }
}
